export interface BrainRegion {
  id: string
  name: string
  nameEn: string
  color: string
  hoverColor: string
  description: string
  symptoms: string[]
  activities: string[]
  nriTechniques: string[]
  emoji: string
}

export const adultsBrainRegions: BrainRegion[] = [
  {
    id: 'frontal',
    name: 'Frontálny lalok',
    nameEn: 'Prefrontálna kôra',
    color: '#1b6b72',
    hoverColor: '#2a9aa8',
    emoji: '🧠',
    description: 'Riaditeľňa mozgu. Zodpovedá za rozhodovanie, sebaovládanie, plánovanie a reguláciu emócií. Pri traume a ADHD je táto oblasť oslabená alebo odpojená od nižších centier.',
    symptoms: [
      'Impulzivita a reaktivita',
      'Ťažkosti s plánovaním a organizáciou',
      'Emočné výbuchy',
      'Prokrastinácia',
      'Ťažkosti s dokončením úloh',
      'Problémy s pozornosťou',
    ],
    activities: [
      'Freeze Dance — stop na signál',
      'Tai-Ji pohyby (pomalá kontrola)',
      'Dychové cvičenia',
      'Pomalé, vedomé pohyby',
    ],
    nriTechniques: [
      'Freeze Dance pri rytmickej hudbe',
      'Inhibičné cvičenia — brzdenie impulzu',
      'Rytmické zastavenia',
      'Vedomé dychové sekvencie',
    ],
  },
  {
    id: 'temporal',
    name: 'Temporálny lalok',
    nameEn: 'Broccovo & Wernickeho centrum',
    color: '#7a2d45',
    hoverColor: '#a04060',
    emoji: '🎵',
    description: 'Centrum pre reč, jazyk a emočnú pamäť. Wernickeho centrum rozumie slovám, Broccovo centrum ich produkuje. Hudobné zážitky a ritmus sa spracúvajú tu.',
    symptoms: [
      'Ťažkosti s rečou a artikuláciou',
      'Problémy s porozumením hovorenému slovu',
      'Dyslexia a dysfázia',
      'Ťažkosti s učením sa nových slov',
      'Emočná pamäť — opakujúce sa trauma spomienky',
    ],
    activities: [
      'Spev slabík a jednoduchých tónov',
      'Rytmické opakovanie slov',
      'Hudobné aktivity',
      'Príbehy v pohybe',
    ],
    nriTechniques: [
      'Tónovanie samohlások A-O-U',
      'Spev syllabík MA-BA-PA',
      'Hudobné zrkadlenie',
      'Rytmická stimulácia v pohybe',
    ],
  },
  {
    id: 'parietal',
    name: 'Parietálny lalok',
    nameEn: 'Senzorické centrum & Telesná mapa',
    color: '#2d5080',
    hoverColor: '#3d70b0',
    emoji: '🤲',
    description: 'Vytvára mapu tela v mozgu. Integruje zmysly — dotyk, polohu, pohyb, priestorovú orientáciu. Pri traumatizovanom nervovom systéme sa telesné uvedomenie stráca.',
    symptoms: [
      'Odpojenie od tela (depersonalizácia)',
      'Senzorické preťaženie alebo precitlivenosť',
      'Ťažkosti s priestorovou orientáciou',
      'Chudobná telesná schéma',
      'Problémy s ľavou/pravou stranou',
    ],
    activities: [
      'Taktilná stimulácia',
      'Proprioceptívne aktivity',
      'Rytmické klepanie po tele',
      'LP — Lost On You (vyklepávanie)',
    ],
    nriTechniques: [
      'Budovanie telesnej mapy (LP protokol)',
      'Rytmické klepanie plecia → kolená',
      'Skrížené pohyby cez stredovú líniu',
      'Hlboký tlak a objatie',
    ],
  },
  {
    id: 'occipital',
    name: 'Okcipitálny lalok',
    nameEn: 'Zrakové centrum',
    color: '#1a4530',
    hoverColor: '#2a6545',
    emoji: '👁️',
    description: 'Spracúva vizuálne informácie — farby, tvary, pohyb, hĺbku. Prepojený s cerebellom pre koordináciu oka a tela. Vizuálne traumy a flashbacky súvisia s touto oblasťou.',
    symptoms: [
      'Vizuálna precitlivenosť',
      'Ťažkosti so sledovaním pohybujúcich sa objektov',
      'Flashbacky a vizuálne rušenie',
      'Problémy s čítaním (tracking)',
      'Dezorientácia pri pohybe',
    ],
    activities: [
      'Sledovanie pomalého pohybu ruky',
      'Periférna vizuálna aktivácia',
      'Rytmický pohyb so zrakovým vedením',
    ],
    nriTechniques: [
      'Pomalé sledovanie pohybu',
      'Periférna stimulácia pohľadu',
      'Rytmické pohyby s vizuálnym kontaktom',
    ],
  },
  {
    id: 'cerebellum',
    name: 'Mozoček',
    nameEn: 'Cerebellum',
    color: '#4a3080',
    hoverColor: '#6040a8',
    emoji: '⚖️',
    description: 'Centrum koordinácie, rovnováhy a časovania pohybov. Trénovaný pomalými, plynulými pohybmi ako Tai-Ji. U detí s ADHD, PVL a CPP je najčastejšie oslabený.',
    symptoms: [
      'Neohrabanosť a problémy s koordináciou',
      'Ťažkosti s rovnováhou',
      'Problémy s jemnou motorikou',
      'Poruchy písania a kreslenia',
      'Ataxia a trhané pohyby',
    ],
    activities: [
      'Tai-Ji pohyby (pomalé a plynulé)',
      'Stoj na jednej nohe',
      'Rytmické prenášanie váhy',
      'Evanescence — My Immortal (ultra-pomalý pohyb)',
    ],
    nriTechniques: [
      'Tai-Ji séria — maximum kontroly',
      'Pomalé prenášanie váhy ľavá↔pravá',
      'Rovnovážne aktivity s očami zatvorenými',
      'Koordinačné sekvencie',
    ],
  },
  {
    id: 'brainstem',
    name: 'Mozgový kmeň',
    nameEn: 'Amygdala & Mozgový kmeň',
    color: '#7a4020',
    hoverColor: '#a05528',
    emoji: '🌊',
    description: 'Najstaršia časť mozgu. Riadi základné prežitie — dýchanie, srdcový rytmus, reakcie boj/útek/zamrzni. Tu sídli trauma. Rytmus a predvídateľnosť sú kľúče k zmene.',
    symptoms: [
      'Chronická úzkosť a hypervigilancia',
      'Freeze reakcie — zamrznutie',
      'Autonómna dysregulácia',
      'Poruchy spánku',
      'Chronické napätie v tele',
      'Panic ataky',
    ],
    activities: [
      'Hlboké dychové cvičenia',
      'Rytmická stabilizácia (60 BPM)',
      'Mrmlanie hlásky M',
      'Pevný rituál a predvídateľnosť',
    ],
    nriTechniques: [
      'Lady Gaga — Hold My Hand (naladenie)',
      'Dychový rytmus — nádych 4 doby, výdych 6 dôb',
      'Tónovanie samohlások U-O',
      'Fixné poradie skladieb ako rituál bezpečia',
    ],
  },
  {
    id: 'limbic',
    name: 'Limbický systém',
    nameEn: 'Hipokampus & Amygdala',
    color: '#1a5060',
    hoverColor: '#2a7080',
    emoji: '❤️',
    description: 'Emočné centrum mozgu. Amygdala detekuje nebezpečenstvo, hipokampus ukladá spomienky. Trauma uviazne tu — bez slov, len ako pocity v tele.',
    symptoms: [
      'Úzkosť a strach bez jasnej príčiny',
      'Emočné preplavenie',
      'Traumatické spomienky a flashbacky',
      'Problémy s dôverou a vzťahmi',
      'Depresia a chronický smútok',
      'Disociácia',
    ],
    activities: [
      'Zrkadlenie pohybov — budovanie dôvery',
      'Edith Piaf — Non, je ne regrette rien',
      'Mrmlanie a hlasové tónovanie',
      'Koregulácia — zdieľaný pokoj',
    ],
    nriTechniques: [
      'Zrkadlový protokol — odborník kopíruje pohyby',
      'Tónovanie O — otváranie srdca',
      'Pomalé húpanie a koregulácia',
      'Rituál bezpečia — rovnaké poradie',
    ],
  },
  {
    id: 'thalamus',
    name: 'Talamus',
    nameEn: 'Talamus — centrálna stanica',
    color: '#2a4860',
    hoverColor: '#3a6888',
    emoji: '📡',
    description: 'Centrálna prepojovacia stanica mozgu. Filtruje všetky zmyslové vstupy a rozhoduje, čo postúpi do vedomia. Pri traumatickom strese je "filter" posunutý — prepúšťa príliš veľa alebo príliš málo.',
    symptoms: [
      'Senzorická precitlivenosť alebo otupenie',
      'Problémy s filtrovaním rušivých podnetov',
      'Hypervigilancia — bdenie na všetko',
      'Senzorická integračná porucha',
    ],
    activities: [
      'Proprioceptívna stimulácia',
      'Hlboký tlak a ohraničenie',
      'Rytmické predvídateľné vstupy',
    ],
    nriTechniques: [
      'Postupná senzorická desenzitizácia',
      'Rytmická stimulácia so stabilným tempom',
      'Hlboká proprioceptívna práca',
    ],
  },
  {
    id: 'basalganglia',
    name: 'Bazálne gangliá & Striatum',
    nameEn: 'Bazálne gangliá',
    color: '#3d2060',
    hoverColor: '#5a3088',
    emoji: '🎯',
    description: 'Filter pohybov a návykov. Striatum je centrum pre automatické pohyby, odmeny a motiváciu. Zapojené pri ADHD, tikoch a OCD. Pracujú na rytme 100-120 BPM.',
    symptoms: [
      'Tiky a stereotypné pohyby',
      'Problémy s automatizáciou pohybu',
      'Motivačné ťažkosti (ADHD)',
      'Rigidné myslenie',
      'Problémy s plynulosťou pohybu',
    ],
    activities: [
      'Queen — We Will Rock You (dupanie)',
      'Rytmické búchanie na bubon',
      'Pochodovanie v rytme',
    ],
    nriTechniques: [
      'Bazálna ganglia stimulácia — 100-120 BPM',
      'Silné rytmické dupanie',
      'Tlieskanie dup-dup-plesk vzorec',
      'Rhythmic Entrainment',
    ],
  },
  {
    id: 'corpus',
    name: 'Corpus Callosum',
    nameEn: 'Medzimozgové spojenie',
    color: '#1a5a40',
    hoverColor: '#2a8060',
    emoji: '🔗',
    description: 'Biela hmota, ktorá prepája ľavú a pravú hemisféru. Pri PVL (periventrikulárnej leukomalácii) môže byť poškodená. Cvičenia, kde ruky prechádzajú cez stredovú líniu, priamo budujú nové dráhy.',
    symptoms: [
      'Lateralizačné problémy (neistá dominancia rúk)',
      'Koordinačné ťažkosti',
      'Ťažkosti so skríženými pohybmi',
      'Problémy s integráciou ľavej a pravej strany',
      'Periventrikulárna leukomalalácia (PVL)',
    ],
    activities: [
      'Skrížené pohyby cez stredovú líniu',
      '"Hladkanie oblakov" — ruky sa míňajú',
      'Imagine Dragons — Demons',
      'Tai-Ji séria so skríženými pohybmi',
    ],
    nriTechniques: [
      'Bilaterálne skrížené sekvencie',
      'Pohyb cez stredovú os tela',
      'Pravá ruka → ľavé koleno a naopak',
      'Hemisferická integrácia cez pohyb',
    ],
  },
]

export const kidsBrainRegions: BrainRegion[] = [
  {
    id: 'frontal',
    name: 'Čelný lalok',
    nameEn: 'Riaditeľňa mozgu',
    color: '#2b8a62',
    hoverColor: '#3db882',
    emoji: '🏆',
    description: 'Toto je „šéf" mozgu! Pomáha nám premýšľať pred konaním, ovládať sa a plánovať. U niektorých detí sa vyvíja pomalšie – a to je v poriadku!',
    symptoms: [
      'Impulzívne reakcie — konanie bez premýšľania',
      'Ťažkosti so čakaním (rad, hra)',
      'Výbuchy hnevu',
      'Problémy s dokončením úloh',
      'Ťažkosti s novými situáciami',
      'ADHD prejavy',
    ],
    activities: [
      '🎮 Freeze Dance — stopuj sa na signál',
      '🐯 Hra na tigra — tlačenie rúk',
      '🌊 Pomalý Tai-Ji pohyb',
      '🎵 Rammstein stop hra',
    ],
    nriTechniques: [
      'Freeze Dance tréning (frontálny lalok)',
      'Inhibičné hry — "červená/zelená"',
      'Pomalé kontrolované pohyby',
      'Dychová kotva pred akciou',
    ],
  },
  {
    id: 'temporal',
    name: 'Spánkový lalok',
    nameEn: 'Centrum reči a zvukov',
    color: '#e8724a',
    hoverColor: '#f09060',
    emoji: '🎤',
    description: 'Tu mozog rozumie slovám a zvukom! Broccovo centrum hovorí slová, Wernickeho centrum im rozumie. Hudba a rytmus pomáhajú trénovať tento lalok.',
    symptoms: [
      'Oneskorený vývoj reči',
      'Ťažkosti s porozumením pokynov',
      'Dyslália (nesprávna výslovnosť)',
      'Problémy s učením sa slov',
      'Precitlivenosť na zvuky',
    ],
    activities: [
      '🎵 Spev slabík MA-BA-PA',
      '🎶 Rytmické básničky',
      '🥁 Hra na bubon/tlieskanie',
      '🐠 Príbehy so zvukmi zvierat',
    ],
    nriTechniques: [
      'Vokálne tónovanie A-O-U',
      'Rytmické spevy slabík',
      'Hudobné zrkadlenie',
      'LP — Lost On You (hvízdanie)',
    ],
  },
  {
    id: 'parietal',
    name: 'Temenný lalok',
    nameEn: 'Telesná mapa',
    color: '#3474b8',
    hoverColor: '#4a90d0',
    emoji: '🗺️',
    description: 'Temenný lalok si tvorí "mapu tela" — vie, kde sú všetky časti tela a čo cítia. Keď je táto mapa nepresná, dieťa môže pôsobiť neohrabane.',
    symptoms: [
      'Neohrabanosť a narážanie do vecí',
      'Ťažkosti s obliekaním (gombíky, šnúrky)',
      'Senzorická precitlivenosť',
      'Problémy s priestorovou orientáciou',
      'Hypersenzitivita na dotyky',
    ],
    activities: [
      '🤲 Klepanie po tele v rytme',
      '🎨 Maľovanie rukami',
      '⚽ Hry s loptou',
      '🌊 Masáž a hlboký dotyk',
    ],
    nriTechniques: [
      'Rytmické klepanie tela (LP protokol)',
      'Proprioceptívna stimulácia',
      'Hlboký dotyk a objatie',
      'Skrížené pohyby rúk',
    ],
  },
  {
    id: 'occipital',
    name: 'Záhlavný lalok',
    nameEn: 'Centrum videnia',
    color: '#8060c0',
    hoverColor: '#a080e0',
    emoji: '👀',
    description: 'Záhlavný lalok spracúva všetko, čo vidíme! Spolupracuje s mozočkom, aby sme vedeli trafiť loptou alebo prechádzať cez dvere bez narážania.',
    symptoms: [
      'Ťažkosti so sledovaním pohybujúcich predmetov',
      'Problémy s čítaním (preskakuje riadky)',
      'Dezorientácia pri pohybe',
      'Ťažkosti s diaľkovým odhadom',
    ],
    activities: [
      '🌊 Sledovanie pomalého pohybu ruky',
      '🔮 Vizuálne sledovanie loptičky',
      '🎯 Hry s terčom na rôznych vzdialenostiach',
    ],
    nriTechniques: [
      'Vestibulárno-vizuálna integrácia',
      'Pomalé vizuálne sledovanie',
      'Periférny pohľad a orientácia',
    ],
  },
  {
    id: 'cerebellum',
    name: 'Mozoček',
    nameEn: 'Centrum rovnováhy',
    color: '#c8980a',
    hoverColor: '#e0b820',
    emoji: '⚖️',
    description: 'Mozoček je ako "auto-pilot" tela — stará sa o rovnováhu a koordináciu. Trénujeme ho pomalými, plynulými pohybmi ako Tai-Ji alebo tanec.',
    symptoms: [
      'Problémy s rovnováhou (pádanie)',
      'Neohrabané pohyby',
      'Ťažkosti s bicyklom/kolobežkou',
      'Problémy s jemnou motorikou',
      'Ťažkosti so zorientovaním v priestore',
    ],
    activities: [
      '🌳 "Strom v rannom vánku"',
      '🐱 Chôdza po čiare',
      '🏄 Balansovanie na podložke',
      '⛅ "Hladkanie oblakov" — Tai-Ji',
    ],
    nriTechniques: [
      'Tai-Ji 5-minútová ranná rutina',
      '"Strom" — uzemnenie a rovnováha',
      'Pomalé prenášanie váhy',
      'Evanescence — My Immortal (ultra-pomalý pohyb)',
    ],
  },
  {
    id: 'brainstem',
    name: 'Mozgový kmeň',
    nameEn: 'Centrum bezpečia',
    color: '#c85030',
    hoverColor: '#e06848',
    emoji: '🏠',
    description: 'Mozgový kmeň je najstaršia časť mozgu — "dom" nervového systému. Keď sa cíti nebezpečne, spustí alarm. Rituál a predvídateľnosť mu hovoria: "Si v bezpečí!"',
    symptoms: [
      'Výbuchy bez viditeľnej príčiny',
      'Problémy so spánkom',
      'Extrémna reakcia na zmeny',
      'Hypervigilancia — strach z nového',
      'Freeze — zamrznutie, nereagovanie',
    ],
    activities: [
      '🏡 Ranný rituál (vždy rovnaký)',
      '🎵 Fixná NRI playlist (vždy rovnaké poradie)',
      '🌬️ Dych do bruška',
      '🤗 Mrmlanie MMM pri objatí',
    ],
    nriTechniques: [
      'Rituál a predvídateľná štruktúra',
      'Lady Gaga — Hold My Hand (naladenie)',
      'Mrmlanie M pri hlbokom objatí',
      'Dýchanie v rytme 4-6 dôb',
    ],
  },
  {
    id: 'basalganglia',
    name: 'Bazálne gangliá',
    nameEn: 'Centrum pohybu a rytmu',
    color: '#1b6b72',
    hoverColor: '#2a9aa8',
    emoji: '🥁',
    description: 'Bazálne gangliá milujú rytmus! Pomáhajú telu pohybovať sa plynule a automaticky. Keď sú oslabené, pohyb je trhaný. Queen — We Will Rock You ich priamo aktivuje!',
    symptoms: [
      'Tiky a stereotypné pohyby',
      'Trhaný, nepresný pohyb',
      'Ťažkosti s automatickým pohybom',
      'Rigidné myslenie',
      'Problémy s pozornosťou',
    ],
    activities: [
      '🥁 Dup-dup-PLESK! (Queen)',
      '🎵 Búchanie na bubon',
      '👣 Pochodovanie v rytme',
      '👏 Rytmické tlieskanie',
    ],
    nriTechniques: [
      'Queen — We Will Rock You (bazálna stimulácia)',
      'Rytmické dupanie na podložke',
      'Entrainment — synchronizácia s rytmom',
      '100-120 BPM pohybová aktivácia',
    ],
  },
  {
    id: 'corpus',
    name: 'Corpus Callosum',
    nameEn: 'Most medzi hemisférami',
    color: '#2d5080',
    hoverColor: '#3d70b0',
    emoji: '🌉',
    description: 'Corpus Callosum je most medzi ľavou a pravou polovicou mozgu. Keď je tento most slabší (napr. pri PVL), pohyby cez stredovú líniu ho pomáhajú posilniť.',
    symptoms: [
      'Nejasná dominancia rúk',
      'Ťažkosti so skríženými pohybmi',
      'Problémy s koordináciou ľavá-pravá',
      'PVL (periventrikulárna leukomalalácia)',
    ],
    activities: [
      '🌊 "Hladkanie oblakov" — ruky sa krížia',
      '🎵 Skrížené pohyby rúk na hudbu',
      '🤸 Pravé koleno + ľavý lakeť',
      '🌈 Maľovanie oboma rukami naraz',
    ],
    nriTechniques: [
      'Bilaterálne skrížené pohyby',
      '"Hladkanie oblakov" z Tai-Ji setu',
      'Imagine Dragons — Demons (skrížené)',
      'Pohyb cez stredovú os tela',
    ],
  },
]
